language: python
python:
- '3.6'
- '3.8'
cache: pip
install:
- pip install -r requirements.txt
script:
- python -m unittest discover -v
- coverage run  -m unittest discover
- coverage report  src/hello/*
- python setup.py sdist
before_deploy:
- export RELEASE_PKG_FILE=$(ls dist/hello-*.tar.gz)
- echo "deploying $RELEASE_PKG_FILE to GitHub releases"
deploy:
  provider: releases
  file_glob: true
  file: "${RELEASE_PKG_FILE}"
  skip_cleanup: 'true'
  on:
    tags: true
  api_key:
    secure: HKgWkiao2agv90EisYO/1ctgIMqwJTIz8RpezGZUDx3aRRE5XQ+6fnuoyp0wz6uywt2H3iUcdAeeCoHZKl/hA6LjYdCuB/TP/ufZFPF/EsCBbMdloPk1z84Zow89pVcsrSPO7B0TXMYYZ0vGBQAKthxHougkqMhkvdlDohLpOyEmU0rw9gJYsBkdFfF1ItmvjgECMtAOv7xFGBTydoSmVJhjYwU8u9QAUO9PrVCJzADvD9GbHfS4zZ4FJeMgGoQukVIvvh5sWBJ/Gn2gTNPjvKoqBXSHutTzMVzqwfSigtFIjA5miPl9lFii7QAuHJOG4Jw/bfdBtqJcfsDUBaZTgcU3ceh7H1mvbOEWcEBdtHz14LF7vtlPshJqhxsJ8h9J3K24HH403xN8ibNcYEeBvb0d2DehGm9BrgkiRbw9CsRq9eQ1W1NT5lXxT9KSX8rtvlc806jkMzr072TTjdVX2c58v9q1njCeiMJ4qde5DZ8bsW4YWLuwWUf63Ng+cAp/6CcjG4rL3im5Abh8ugJ+/kFZKPsGgrED7ldI4179XuI91wv6Rv1f5+J8jtpucipt3Z4YmIYQDaKzOx5QiuI0rfgC2+9cYwQAQ3MAHzvJlmzNVz8704RzYQ1u3RGKaJLB0b9iRIwQNGJxxtt0JXXHC75p763Qfgyjp3WP+AEu5QA=

